site_name: ''
theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    primary: black
    accent: indigo
  logo: assets/logo_white.svg
  favicon: assets/favicon.png
  font:
    text: Roboto
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
extra_css:
  - stylesheets/extra.css
copyright: Copyright &copy; 2025 Stift LTDA
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - index.md
  - users.md
  - groups.md
  - bookings.md
  - disciplines.md
  - auth_integration.md
  - webhooks.md
  - reports.md
  - exams.md
